#!/bin/sh
#
# Start/stop server script
#
SERVER_NAME=mpv
start() {
	echo -n "Starting $SERVER_NAME Service: "
	/bin/mpv --fs --image-display-duration=5 /Pictures/PlayList.m3u --loop-playlist=inf &
	echo "OK"
}

stop() {
	echo -n "Stopping $SERVER_NAME Service:  "
	killall $SERVER_NAME
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
