#!/bin/sh
#
# Start logging
#
STTNGS_PARTITION=/dev/mmcblk0p4
TARGET_MOUNT_POINT=/mnt/.settings
start() {
	echo -n "Mounting Settings Partition: "
	mount $STTNGS_PARTITION $TARGET_MOUNT_POINT
	echo "OK"
}

stop() {
	echo -n "Unmounting Settings Partition: "
	umount $TARGET_MOUNT_POINT
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
